version: '3.7'

x-env: &env
  RAILS_LOG_TO_STDOUT: 1
  PORT: 3000
  RAILS_MAX_THREADS: 5

  DATABASE_HOST: db
  DATABASE_USER: postgres
  DATABASE_PASS: postgres

services:
  db:
    image: postgres:10.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  api:
    build: .
    command: rails s -b '0.0.0.0'
    tty: true
    stdin_open: true
    environment:
      <<: *env
      DATABASE_NAME: maximo-service-db
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - 3000:3000
    # depends_on:
    #   - db
volumes:
  bundle:
